config/routes.rb
Rails.application.routes.draw do

  resources :cities do
    member do
      get 'rentals'
    end
  end

  resources :kinds

  resources :users do
    resources :rentals do
      resources :reviews
    end
  end

  root to: 'users#index'
end

app/models/rental.rb
class Rental < ActiveRecord::Base
  belongs_to :city
  belongs_to :kind
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :availabilities, dependent: :destroy
  has_many :pictures, class_name: 'RentalPicture', dependent: :destroy
  accepts_nested_attributes_for :availabilities, allow_destroy: true

  def self.all_by_availability(start_date, end_date)
    start_date = start_date.to_date
    end_date = end_date.to_date
    nb_days = (end_date - start_date).to_i

    sql = %(
      SELECT rental_id
      FROM (
        SELECT COUNT(*) AS count_all, rental_id AS rental_id
        FROM "availabilities"
        WHERE (DATE(availabilities.day) >= DATE(?) AND DATE(availabilities.day) <  DATE(?))
        GROUP BY "availabilities"."rental_id"
      ) AS tmp
      WHERE tmp.count_all = ?
    )

    Rental.joins(%(
      INNER JOIN (#{ActiveRecord::Base.send(:sanitize_sql_array, [sql, start_date, end_date, nb_days])})
      AS rentals_tmp
      ON rentals.id = rentals_tmp.rental_id
    ))
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_rental, only: [:show, :edit, :update, :destroy]

  # GET /rentals
  # GET /rentals.json
  def index
    @user = User.find(params[:user_id])
    @rentals = @user.rentals.all
  end

  # GET /rentals/1
  # GET /rentals/1.json
  def show
  end

  # GET /rentals/new
  def new
    @user = User.find(params[:user_id])
    @rental = @user.rentals.build
  end

  # GET /rentals/1/edit
  def edit
  end

  # POST /rentals
  # POST /rentals.json
  def create
    @rental = Rental.new(rental_params)

    respond_to do |format|
      if @rental.save
        if params[:images]
          params[:images].each do |image|
            @rental.pictures.create(file: image)
          end
        end

        format.html { redirect_to [@rental.user, @rental], notice: 'Rental was successfully created.' }
        format.json { render :show, status: :created, location: [@rental.user, @rental] }
      else
        format.html { render :new }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rentals/1
  # PATCH/PUT /rentals/1.json
  def update
    respond_to do |format|
      if @rental.update(rental_params)
        if params[:images]
          @rental.pictures.destroy_all
          params[:images].each do |image|
            @rental.pictures.create(file: image)
          end
        end

        format.html { redirect_to [@rental.user, @rental], notice: 'Rental was successfully updated.' }
        format.json { render :show, status: :ok, location: [@rental.user, @rental] }
      else
        format.html { render :edit }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rentals/1
  # DELETE /rentals/1.json
  def destroy
    @rental.destroy
    respond_to do |format|
      format.html { redirect_to user_rentals_url, notice: 'Rental was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rental
      @rental = Rental.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rental_params
      params.require(:rental).permit(:name, :city_id, :kind_id, :nb_guests, :score, :user_id, :price, :instant_book,
                                     :lat, :lng, availabilities_attributes: [:id, :day, :_destroy])
    end
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/rentals/_availability_fields.html.erb
<fieldset>
  <%= f.label :day, "Available Date" %><br />
  <%= f.text_field :day, placeholder: 'dd/mm/yyyy' %><br />
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, "Remove Date" %>
</fieldset>

app/views/rentals/_form.html.erb
<%= form_for [@rental.user, @rental], html: { multipart: true } do |f| %>
  <%= f.hidden_field :user_id, value: @rental.user_id %>

  <% if @rental.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rental.errors.count, "error") %> prohibited this rental from being saved:</h2>

      <ul>
      <% @rental.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.collection_select(:city_id, City.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.collection_select(:kind_id, Kind.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :nb_guests %><br>
    <%= f.number_field :nb_guests %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.text_field :score %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :instant_book %><br>
    <%= f.check_box :instant_book %>
  </div>
  <div class="field">
    <%= f.label :lat, "Latitude" %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng, "Longitude" %><br>
    <%= f.text_field :lng %>
  </div>
  <div class="field">
    <%= file_field_tag "images[]", type: :file, multiple: true %>
  </div>
  <div class="field">
    <%= f.fields_for :availabilities do |builder| %>
      <%= render 'availability_fields', f: builder %>
    <% end %>
    <%= link_to_add_fields "Add Available Date", f, :availabilities %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rentals/edit.html.erb
<h1>Editing Rental</h1>

<%= render 'form' %>

<%= link_to 'Show', [@rental.user, @rental] %> |
<%= link_to 'Back', user_rentals_path %>

app/views/rentals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rentals</h1>

<table cellpadding="4">
  <thead>
    <tr>
      <th>Name</th>
      <th>Kind</th>
      <th>Score</th>
      <th>User</th>
      <th>Price</th>
      <th>Instant<br/> book</th>
      <th>Reviews</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rentals.each do |rental| %>
      <tr>
        <td><%= rental.name %></td>
        <td><%= rental.kind.name %></td>
        <td style="text-align: center"><%= rental.score || 0 %>/5</td>
        <td><%= rental.user.full_name %></td>
        <td style="text-align: center">$<%= rental.price || 0.0 %></td>
        <td style="text-align: center"><%= rental.instant_book %></td>
        <td style="text-align: center"><%= link_to rental.reviews.count, user_rental_reviews_path(rental.user, rental) %></td>
        <td><%= link_to 'Show', user_rental_path(rental.user, rental) %></td>
        <td><%= link_to 'Edit', edit_user_rental_path(rental.user, rental) %></td>
        <td><%= link_to 'Destroy', user_rental_path(rental.user, rental), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if @user %>
  <br>

  <%= link_to 'New Rental', new_user_rental_path %> |
  <%= link_to 'Back to user', user_path(@user) %>
<% end %>

app/views/rentals/new.html.erb
<h1>New Rental</h1>

<%= render 'form' %>

<%= link_to 'Back', user_rentals_path %>

app/views/rentals/show.html.erb
<div class="rental">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @rental.name %>
  </p>

  <p>
    <strong>City:</strong>
    <%= @rental.city.name %>
  </p>

  <p>
    <strong>Kind:</strong>
    <%= @rental.kind.name %>
  </p>

  <p>
    <strong>Nb Guests:</strong>
    <%= @rental.nb_guests %>
  </p>

  <p>
    <strong>Score:</strong>
    <%= @rental.score %>
  </p>

  <p>
    <strong>User:</strong>
    <%= @rental.user.full_name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= @rental.price %>
  </p>

  <p>
    <strong>Instant book:</strong>
    <%= @rental.instant_book %>
  </p>

  <p>
    <strong>Latitude:</strong>
    <%= @rental.lat %>
  </p>

  <p>
    <strong>Longitude:</strong>
    <%= @rental.lng %>
  </p>

  <p>
    <strong>Reviews (<%= @rental.reviews.count %>):</strong>

    <ul>
      <% @rental.reviews.each do |review| %>
        <%= content_tag :li do %>
          <%= image_tag review.user.avatar(:thumb), size: '30x30' %>
          <%= review.user.full_name %> <br />
          <%= review.content %>
        <% end %>
      <% end %>
    </ul>
  </p>

  <div class="pictures">
    <strong>Pictures (<%= @rental.pictures.count %>):</strong>

    <ul>
      <% @rental.pictures.each do |picture| %>
        <%= content_tag :li, image_tag(picture.file(:thumb)) %>
      <% end %>
    </ul>
  </div>

  <p>
    <strong>Availability (<%= @rental.reviews.count %>):</strong>

    <ul>
      <% @rental.availabilities.each do |availability| %>
        <%= content_tag :li, availability.day %>
      <% end %>
    </ul>
  </p>
</div>

<%= link_to 'Edit', edit_user_rental_path(@rental.user, @rental) %> |
<%= link_to 'Back', user_rentals_path %> |
<%= link_to 'Add review', new_user_rental_review_path(@rental.user, @rental) %>