config/routes.rb
Rails.application.routes.draw do

  resources :cities do
    member do
      get 'rentals'
    end
  end

  resources :kinds

  resources :users do
    resources :rentals do
      resources :reviews
    end
  end

  root to: 'users#index'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @rental = Rental.find(params[:rental_id])
    @reviews = @rental.reviews.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @rental = Rental.find(params[:rental_id])
    @review = @rental.reviews.build
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to [@review.rental.user, @review.rental, @review], notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: [@review.rental.user, @review.rental, @review] }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to [@review.rental.user, @review.rental, @review], notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: [@review.rental.user, @review.rental, @review] }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to user_rental_reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rental_id, :user_id, :content)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for([@review.rental.user, @review.rental, @review]) do |f| %>
  <%= f.hidden_field :rental_id, value: @review.rental_id %>

  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.collection_select(:user_id, User.all, :id, :full_name) %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', [@review.rental.user, @review.rental, @review] %> |
<%= link_to 'Back', user_rental_reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @rental.name %></h1>

<h1>Listing Reviews</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.user.full_name %></td>
        <td><%= review.content %></td>
        <td><%= link_to 'Show', [review.rental.user, review.rental, review] %></td>
        <td><%= link_to 'Edit', edit_user_rental_review_path(review.rental.user, review.rental, review) %></td>
        <td><%= link_to 'Destroy', [review.rental.user, review.rental, review], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_user_rental_review_path %> |
<%= link_to 'Back to rental', user_rental_path(@rental.user, @rental) %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', user_rental_reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rental:</strong>
  <%= @review.rental.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @review.user.full_name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @review.content %>
</p>

<%= link_to 'Edit', edit_user_rental_review_path(@review.rental.user, @review.rental, @review) %> |
<%= link_to 'Back', user_rental_reviews_path %>